### ISSUE TITLE
Trying to replicate "Experimental Evaluation of Visual-Inertial Odometry Systems for Arable Farming" results with ORB-SLAM3

### ISSUE THREAD

**Issue by ghost** [CIFASIS/slam_agricultural_evaluation#2]
I tried to replicate "Experimental Evaluation of Visual-Inertial Odometry Systems for Arable Farming" experiments with ORB-SLAM 3 using a ROS wrapper (https://github.com/thien94/orb_slam3_ros_wrapper), but I could not create a proper map just modifying the ".yaml" file. Is it needed to change something in the ORB-SLAM 3 code to make it work?

I've attached my ".yaml" and ".launch" files below.
[Rosario.zip](https://github.com/CIFASIS/slam_agricultural_evaluation/files/10218908/Rosario.zip)
[ros_stereoimu.zip](https://github.com/CIFASIS/slam_agricultural_evaluation/files/10218911/ros_stereoimu.zip)

**Comment by jcremona** [comment]
Dear @yriuss,

Please note that we have modified the ORB-SLAM3 code to make a fairer comparison against Visual Odometry systems. As the paper says: we modified the ORB-SLAM3 ROS wrapper to publish the estimated pose as soon as a frame is properly tracked. Please let me know if you need help to run our modified version of ORB-SLAM3.

**Comment by jcremona** [comment]
Closed due to inactivity.
