### ISSUE TITLE
hardware clock synchronization

### ISSUE THREAD

**Issue by lessless66** [CIFASIS/slam_agricultural_evaluation#3]
I see that all the sensors are synchronized by software. Does sensors do hardware clock synchronization?

**Comment by jcremona** [comment]
Hi! For more information, please check the article "The Rosario Dataset: Multisensor Data for Localization and Mapping in Agricultural Environments"
https://robot.cifasis-conicet.gov.ar/images/d/d2/Rosariodataset2019.pdf
